spring:
  application:
    name: DearPet

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dearpetdb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin

  # jpa:
    # hibernate:
      # ddl-auto: update
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
    # show-sql: false
    # open-in-view: false

  logging:
    level:
      root: INFO

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    favicon: favicon.ico
